spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cshr
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: update # update schema on run. Use "create-drop" to reset schema on every run
server:
  port: 8080
